name: OpenSSF Scorecard

on:
  schedule:
    - cron: '0 0 * * 0' # weekly
  push:
    branches: [main]

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write

    steps:
      - name: Run Scorecards analysis
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
      - name: Upload Scorecards results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
